package mcpproxy

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"harness/internal/cli"
	"harness/internal/configmeta"
)

func configFlagValues(t *testing.T, args ...string) cli.Values {
	t.Helper()
	catalog := cli.MustCatalog(cli.Command{ID: "test", Name: "test", Runnable: true, Flags: CLIFlags()})
	invocation, err := catalog.Parse(args)
	if err != nil {
		t.Fatalf("parse config flags %v: %v", args, err)
	}
	return invocation.Flags
}

func TestConfigCatalogMetadataAndCLICompleteness(t *testing.T) {
	wantKeys := []string{"mcp_servers", "listen", "log_file", "log_level", "log_format", "api_keys_file", "metrics_enabled", "metrics_listen"}
	parameters := Catalog().Parameters()
	gotKeys := make([]string, len(parameters))
	for i, parameter := range parameters {
		gotKeys[i] = parameter.Key
	}
	if !reflect.DeepEqual(gotKeys, wantKeys) {
		t.Fatalf("catalog keys = %v, want %v", gotKeys, wantKeys)
	}
	servers, _ := Catalog().Lookup("mcp_servers")
	if servers.JSONPath != "mcpServers" || servers.Type != "object" || !servers.Sensitive {
		t.Fatalf("mcp_servers metadata = %+v", servers)
	}
	level, _ := Catalog().Lookup("log_level")
	if !reflect.DeepEqual(level.Accepted, []string{"debug", "info", "warn", "warning", "error"}) {
		t.Fatalf("log_level accepted = %v", level.Accepted)
	}

	settingFlags := SettingCLIFlags()
	if len(settingFlags) != len(wantKeys)-1 {
		t.Fatalf("setting flag count = %d, want %d", len(settingFlags), len(wantKeys)-1)
	}
	seen := make(map[string]bool)
	for _, flag := range settingFlags {
		seen[flag.ID] = true
	}
	for _, key := range wantKeys[1:] {
		parameter, _ := Catalog().Lookup(key)
		if len(parameter.Flags) > 0 && !seen[key] {
			t.Errorf("catalog flag for %q missing from SettingCLIFlags", key)
		}
	}
	all := CLIFlags()
	if all[0].ID != "config" || len(all) != len(settingFlags)+1 {
		t.Fatalf("CLIFlags = %+v", all)
	}
	all[0].Names[0] = "mutated"
	if CLIFlags()[0].Names[0] != "config" {
		t.Fatal("CLIFlags did not return a defensive copy")
	}
}

func TestGeneratedMCPReferenceTableIsCurrent(t *testing.T) {
	docPath := filepath.Join("..", "..", "docs", "mcp.md")
	document, err := os.ReadFile(docPath)
	if err != nil {
		t.Fatal(err)
	}
	const startMarker = "<!-- mcp-proxy-config-parameters:start -->"
	const endMarker = "<!-- mcp-proxy-config-parameters:end -->"
	start := bytes.Index(document, []byte(startMarker))
	end := bytes.Index(document, []byte(endMarker))
	if start < 0 || end < 0 || end < start {
		t.Fatalf("%s is missing ordered config reference markers", docPath)
	}
	end += len(endMarker)

	var generated bytes.Buffer
	generated.WriteString(startMarker + "\n")
	if err := configmeta.WriteMarkdown(&generated, Catalog()); err != nil {
		t.Fatal(err)
	}
	generated.WriteString(endMarker)
	if got := string(document[start:end]); got != generated.String() {
		t.Fatalf("generated config reference in %s is stale; regenerate it with `harness-mcp-proxy config list -format markdown`", docPath)
	}
}

func TestResolveConfigMissingPathSemanticsAndDerivedDefaults(t *testing.T) {
	home := t.TempDir()
	getenv := func(name string) string {
		if name == "HOME" {
			return home
		}
		return ""
	}
	result, err := ResolveConfig(ResolveOptions{Getenv: getenv})
	if err != nil {
		t.Fatalf("implicit missing default: %v", err)
	}
	wantPath := filepath.Join(home, ".config", "harness-mcp-proxy", "config.json")
	if result.Path != wantPath || result.ConfigLoaded || result.Config.Listen != DefaultListen {
		t.Fatalf("result = %+v", result)
	}
	if got, want := result.Config.APIKeysFile, filepath.Join(filepath.Dir(wantPath), "api_keys.json"); got != want {
		t.Fatalf("APIKeysFile = %q, want %q", got, want)
	}
	if result.Sources["api_keys_file"].Kind != configmeta.SourceDerived || result.Sources["listen"].Kind != configmeta.SourceDefault {
		t.Fatalf("sources = %+v", result.Sources)
	}

	missing := filepath.Join(t.TempDir(), "missing.json")
	if _, err := ResolveConfig(ResolveOptions{Path: missing, PathExplicit: true}); err == nil {
		t.Fatal("explicit missing path succeeded")
	}
	if _, err := ResolveConfig(ResolveOptions{Path: "", PathExplicit: true, Getenv: getenv}); err != nil {
		t.Fatalf("explicit empty path: %v", err)
	}
}

func TestResolveConfigPresenceFlagsPathsAndCanonicalValues(t *testing.T) {
	path := writeConfig(t, `{
		"mcpServers": {},
		"proxy": {
			"listen": "", "logFile": "", "logLevel": "warning", "logFormat": "",
			"api_keys_file": "keys/accepted.json",
			"metrics": {"enabled": false, "listen": ""}
		}
	}`)
	result, err := ResolveConfig(ResolveOptions{Path: path, PathExplicit: true})
	if err != nil {
		t.Fatalf("ResolveConfig file: %v", err)
	}
	if result.Config.Listen != DefaultListen || result.Config.LogLevel != "warn" || result.Config.LogFormat != "json" {
		t.Fatalf("canonical config = %+v", result.Config)
	}
	if result.Config.Metrics.Enabled == nil || *result.Config.Metrics.Enabled {
		t.Fatalf("metrics enabled = %v, want explicit false", result.Config.Metrics.Enabled)
	}
	if result.Config.Metrics.Listen != DefaultMetricsListen || result.MetricsListenExplicit {
		t.Fatalf("metrics listen = %q explicit=%v", result.Config.Metrics.Listen, result.MetricsListenExplicit)
	}
	if got, want := result.Config.APIKeysFile, filepath.Join(filepath.Dir(path), "keys", "accepted.json"); got != want {
		t.Fatalf("file API key path = %q, want %q", got, want)
	}
	for _, key := range []string{"mcp_servers", "log_file", "log_level", "api_keys_file", "metrics_enabled"} {
		if result.Sources[key] != (configmeta.Source{Kind: configmeta.SourceFile, Name: path}) {
			t.Errorf("source[%s] = %+v", key, result.Sources[key])
		}
	}
	for _, key := range []string{"listen", "log_format", "metrics_listen"} {
		if result.Sources[key].Kind != configmeta.SourceDefault {
			t.Errorf("empty file value source[%s] = %+v, want default", key, result.Sources[key])
		}
	}

	cwd := t.TempDir()
	flags := configFlagValues(t,
		"--listen=127.0.0.1:7777", "--log=logs/proxy.log", "--log-level=warning", "--log-format=text",
		"--api-keys-file=state/keys.json", "--no-metrics=false", "--metrics-listen=",
	)
	result, err = ResolveConfig(ResolveOptions{Path: path, PathExplicit: true, Flags: flags, Getwd: func() (string, error) { return cwd, nil }})
	if err != nil {
		t.Fatalf("ResolveConfig flags: %v", err)
	}
	if result.Config.Listen != "127.0.0.1:7777" || result.Config.LogLevel != "warn" || result.Config.LogFormat != "text" {
		t.Fatalf("flag overlays = %+v", result.Config)
	}
	if got, want := result.Config.LogFile, filepath.Join(cwd, "logs", "proxy.log"); got != want {
		t.Errorf("LogFile = %q, want %q", got, want)
	}
	if got, want := result.Config.APIKeysFile, filepath.Join(cwd, "state", "keys.json"); got != want {
		t.Errorf("APIKeysFile = %q, want %q", got, want)
	}
	if !*result.Config.Metrics.Enabled || result.Config.Metrics.Listen != DefaultMetricsListen || !result.MetricsListenExplicit {
		t.Errorf("metrics = %+v explicit=%v", result.Config.Metrics, result.MetricsListenExplicit)
	}
	for _, key := range []string{"listen", "log_file", "log_level", "log_format", "api_keys_file", "metrics_enabled"} {
		if result.Sources[key].Kind != configmeta.SourceFlag {
			t.Errorf("source[%s] = %+v", key, result.Sources[key])
		}
	}
	if result.Sources["metrics_listen"].Kind != configmeta.SourceDefault {
		t.Errorf("empty metrics listener source = %+v, want retained winning default", result.Sources["metrics_listen"])
	}
}

func TestResolveConfigEmptyMetricsListenerRetainsFileProvenance(t *testing.T) {
	path := writeConfig(t, `{"proxy":{"metrics":{"listen":"127.0.0.1:9444"}}}`)
	result, err := ResolveConfig(ResolveOptions{
		Path: path, PathExplicit: true,
		Flags: configFlagValues(t, "--metrics-listen="),
	})
	if err != nil {
		t.Fatal(err)
	}
	if got := result.Config.Metrics.Listen; got != "127.0.0.1:9444" || !result.MetricsListenExplicit {
		t.Fatalf("metrics listener=%q explicit=%v", got, result.MetricsListenExplicit)
	}
	if got := result.Sources["metrics_listen"]; got != (configmeta.Source{Kind: configmeta.SourceFile, Name: path}) {
		t.Fatalf("metrics listener source=%+v, want file", got)
	}
}

func TestResolveConfigWarningsToleranceBypassAndStdio(t *testing.T) {
	_ = os.Unsetenv("MCP_PROXY_TEST_A")
	_ = os.Unsetenv("MCP_PROXY_TEST_Z")
	path := writeConfig(t, `{"mcpServers":{
		"zbad":{"command":""},
		"good":{"command":"/bin/good","args":["${MCP_PROXY_TEST_Z}","${MCP_PROXY_TEST_A}"]},
		"abad":{"type":"bogus"}
	}}`)
	result, err := ResolveConfig(ResolveOptions{Path: path, PathExplicit: true, Stdio: true})
	if err != nil {
		t.Fatalf("ResolveConfig: %v", err)
	}
	if len(result.Config.Servers) != 1 || result.Config.Servers[0].Name != "good" {
		t.Fatalf("servers = %+v", result.Config.Servers)
	}
	if len(result.Config.Warnings) != 4 || !strings.Contains(result.Config.Warnings[0], `"abad"`) || !strings.Contains(result.Config.Warnings[1], `"zbad"`) ||
		!strings.Contains(result.Config.Warnings[2], "MCP_PROXY_TEST_A") || !strings.Contains(result.Config.Warnings[3], "MCP_PROXY_TEST_Z") {
		t.Fatalf("warning order = %v", result.Config.Warnings)
	}
	if result.APIKeysActive || result.MetricsActive || !result.Stdio {
		t.Fatalf("stdio operational state = %+v", result)
	}

	missing := filepath.Join(t.TempDir(), "does-not-exist.json")
	result, err = ResolveConfig(ResolveOptions{Path: missing, PathExplicit: true, BypassConfig: true})
	if err != nil || !result.ConfigBypassed || result.ConfigLoaded {
		t.Fatalf("bypass result=%+v err=%v", result, err)
	}
}

func TestSnapshotRedactsStructuredServerSecrets(t *testing.T) {
	secretValues := []string{"arg-secret", "env-secret", "header-secret", "url-user", "url-pass", "query-secret", "inline-secret"}
	result := ConfigResult{
		Config: Config{
			Servers: []ResolvedServer{
				{Name: "local", Transport: TransportStdio, Command: "/secret/bin", Args: []string{"--token=arg-secret"}, Env: map[string]string{"TOKEN": "env-secret"}},
				{Name: "remote", Transport: TransportHTTP, URL: "https://url-user:url-pass@example.test/mcp?token=query-secret", Headers: map[string]string{"Authorization": "header-secret"}},
			},
			Listen: "127.0.0.1:8766", LogLevel: "info", LogFormat: "json",
			Metrics: MetricsConfig{Enabled: boolPointer(true), Listen: DefaultMetricsListen},
		},
		Sources: map[string]configmeta.Source{"mcp_servers": {Kind: configmeta.SourceFile, Name: "/safe/config.json"}},
	}
	snapshot := Snapshot(result)
	encoded, err := json.Marshal(snapshot.Values)
	if err != nil {
		t.Fatal(err)
	}
	text := string(encoded)
	for _, secret := range secretValues {
		if strings.Contains(text, secret) {
			t.Errorf("snapshot leaked %q: %s", secret, text)
		}
	}
	for _, safe := range []string{"local", "remote", "stdio", "http", `"count":2`} {
		if !strings.Contains(text, safe) {
			t.Errorf("snapshot missing safe metadata %q: %s", safe, text)
		}
	}

	projection := configmeta.Project(Catalog(), snapshot, false)
	projected, _ := json.Marshal(projection)
	if strings.Contains(string(projected), "arg-secret") || !strings.Contains(string(projected), "mcpServers") {
		t.Fatalf("unsafe/invalid projection: %s", projected)
	}
}
