package config

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"

	"harness/internal/cli"
	"harness/internal/configmeta"
	"harness/internal/llm"
)

func TestCatalogCompletenessAndCLIProjection(t *testing.T) {
	wantKeys := []string{
		"provider_configs", "default_context_window", "log_level", "log_format",
		"models_dev_cache_ttl", "drain_delay", "shutdown_timeout", "instance_id",
		"api_keys_file", "metrics_enabled", "metrics_listen",
	}
	parameters := Catalog().Parameters()
	if len(parameters) != len(wantKeys) {
		t.Fatalf("catalog length = %d, want %d", len(parameters), len(wantKeys))
	}
	seenFlags := map[string]string{}
	for i, parameter := range parameters {
		if parameter.Key != wantKeys[i] {
			t.Errorf("parameter %d key = %q, want %q", i, parameter.Key, wantKeys[i])
		}
		if parameter.JSONPath == "" || parameter.Description == "" || parameter.Default.Kind == "" {
			t.Errorf("incomplete metadata for %q: %+v", parameter.Key, parameter)
		}
		for _, name := range parameter.Flags {
			if previous := seenFlags[name]; previous != "" {
				t.Errorf("flag %q used by %q and %q", name, previous, parameter.Key)
			}
			seenFlags[name] = parameter.Key
		}
	}
	if got := parameters[9].Flags; !reflect.DeepEqual(got, []string{"no-metrics"}) {
		t.Fatalf("metrics inverse flags = %v", got)
	}
	settingFlags := SettingCLIFlags()
	if len(settingFlags) != 9 {
		t.Fatalf("setting flags = %d, want 9", len(settingFlags))
	}
	for _, flag := range settingFlags {
		parameter, ok := Catalog().Lookup(flag.ID)
		if !ok || !reflect.DeepEqual(flag.Names, parameter.Flags) {
			t.Errorf("flag projection %q = %+v, parameter = %+v", flag.ID, flag, parameter)
		}
	}
	allFlags := CLIFlags()
	if len(allFlags) != len(settingFlags)+1 || allFlags[0].ID != "config" {
		t.Fatalf("CLIFlags = %+v", allFlags)
	}
	allFlags[0].Names[0] = "mutated"
	if CLIFlags()[0].Names[0] != "config" {
		t.Fatal("CLIFlags returned aliased declarations")
	}
}

func TestGeneratedUsageParameterTableIsCurrent(t *testing.T) {
	usagePath := filepath.Join("..", "..", "..", "docs", "usage.md")
	usage, err := os.ReadFile(usagePath)
	if err != nil {
		t.Fatal(err)
	}
	const startMarker = "<!-- model-proxy-config-parameters:start -->"
	const endMarker = "<!-- model-proxy-config-parameters:end -->"
	start := bytes.Index(usage, []byte(startMarker))
	end := bytes.Index(usage, []byte(endMarker))
	if start < 0 || end < 0 || end < start {
		t.Fatalf("%s is missing ordered config reference markers", usagePath)
	}
	end += len(endMarker)

	var generated bytes.Buffer
	generated.WriteString(startMarker + "\n")
	if err := configmeta.WriteMarkdown(&generated, Catalog()); err != nil {
		t.Fatal(err)
	}
	generated.WriteString(endMarker)
	if got := string(usage[start:end]); got != generated.String() {
		t.Fatalf("generated config reference in %s is stale; regenerate it with `harness-model-proxy config list -format markdown`", usagePath)
	}
}

func TestLoadDefaultsAndSources(t *testing.T) {
	result := load(t, LoadOptions{Getenv: getenv(nil), DeriveInstanceID: fixedInstance("derived-1")})
	if result.Path != "" || result.PathExplicit {
		t.Fatalf("path = %q explicit=%v", result.Path, result.PathExplicit)
	}
	if result.Config.DefaultContextWindow != llm.DefaultContextWindow || result.Config.LogLevel != "info" || result.Config.LogFormat != "json" {
		t.Fatalf("scalar defaults = %+v", result.Config)
	}
	if result.Config.ModelsDevCacheTTL.Duration != 24*time.Hour || result.Config.DrainDelay.Duration != 5*time.Second || result.Config.ShutdownTimeout.Duration != 5*time.Minute {
		t.Fatalf("duration defaults = %+v %+v %+v", result.Config.ModelsDevCacheTTL, result.Config.DrainDelay, result.Config.ShutdownTimeout)
	}
	if !result.Config.ModelsDevCacheTTL.Set || !result.Config.DrainDelay.Set || !result.Config.ShutdownTimeout.Set {
		t.Fatal("effective durations did not retain explicit effective values")
	}
	if result.Config.InstanceID != "derived-1" || result.InstanceIDExplicit || result.Sources["instance_id"].Kind != configmeta.SourceDerived {
		t.Fatalf("instance = %q explicit=%v source=%+v", result.Config.InstanceID, result.InstanceIDExplicit, result.Sources["instance_id"])
	}
	if result.Config.APIKeysFile != "api_keys.json" || result.APIKeysFileExplicit || result.Sources["api_keys_file"].Kind != configmeta.SourceDerived {
		t.Fatalf("api key file = %q explicit=%v source=%+v", result.Config.APIKeysFile, result.APIKeysFileExplicit, result.Sources["api_keys_file"])
	}
	if result.Config.Metrics.Enabled == nil || !*result.Config.Metrics.Enabled || result.Config.Metrics.Listen != defaultMetricsListen || result.MetricsListenExplicit {
		t.Fatalf("metrics defaults = %+v explicit=%v", result.Config.Metrics, result.MetricsListenExplicit)
	}
	for _, parameter := range Catalog().Parameters() {
		if _, ok := result.Sources[parameter.Key]; !ok {
			t.Errorf("missing source for %q", parameter.Key)
		}
	}
}

func TestLoadPrecedenceWinnerValidationAndEmptySemantics(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, dir, `{
		"provider_configs":["providers/secret.json"],
		"default_context_window":64000,
		"log_level":"not-valid",
		"log_format":"text",
		"models_dev_cache_ttl":"12h",
		"drain_delay":"7s",
		"shutdown_timeout":"4m",
		"instance_id":"file-id",
		"api_keys_file":"keys/accepted.json",
		"metrics":{"enabled":false,"listen":"0.0.0.0:9191"},
		"unknown":{"kept":"tolerated"}
	}`)
	flags := parseFlags(t,
		"-log-level", "warn",
		"-log-format=",
		"-models-dev-cache-ttl", "0",
		"-drain-delay", "9s",
		"-instance-id", " flag-id ",
		"-no-metrics=false",
		"-metrics-listen=",
	)
	result := load(t, LoadOptions{
		Path: path, PathExplicit: true, Flags: flags,
		Getenv: getenv(map[string]string{
			drainDelayEnvironment:      "8s",
			shutdownTimeoutEnvironment: "6m",
			instanceIDEnvironment:      "env-id",
		}),
		DeriveInstanceID: fixedInstance("unused"),
	})
	if result.Config.LogLevel != "warn" || result.Sources["log_level"].Kind != configmeta.SourceFlag {
		t.Fatalf("log level = %q source=%+v", result.Config.LogLevel, result.Sources["log_level"])
	}
	if result.Config.LogFormat != "text" || result.Sources["log_format"].Kind != configmeta.SourceFile {
		t.Fatalf("empty log flag overrode file: %q source=%+v", result.Config.LogFormat, result.Sources["log_format"])
	}
	if result.Config.ModelsDevCacheTTL.Duration != 0 || result.Config.DrainDelay.Duration != 9*time.Second || result.Config.ShutdownTimeout.Duration != 6*time.Minute {
		t.Fatalf("duration precedence = ttl %v drain %v shutdown %v", result.Config.ModelsDevCacheTTL.Duration, result.Config.DrainDelay.Duration, result.Config.ShutdownTimeout.Duration)
	}
	if result.Sources["shutdown_timeout"] != (configmeta.Source{Kind: configmeta.SourceEnvironment, Name: shutdownTimeoutEnvironment}) {
		t.Fatalf("shutdown source = %+v", result.Sources["shutdown_timeout"])
	}
	if result.Config.InstanceID != "flag-id" || !result.InstanceIDExplicit || result.Sources["instance_id"].Kind != configmeta.SourceFlag {
		t.Fatalf("instance = %q explicit=%v source=%+v", result.Config.InstanceID, result.InstanceIDExplicit, result.Sources["instance_id"])
	}
	if result.Config.Metrics.Enabled == nil || !*result.Config.Metrics.Enabled || result.Sources["metrics_enabled"].Kind != configmeta.SourceFlag {
		t.Fatalf("inverse metrics = %+v source=%+v", result.Config.Metrics, result.Sources["metrics_enabled"])
	}
	if result.Config.Metrics.Listen != "0.0.0.0:9191" || !result.MetricsListenExplicit || result.Sources["metrics_listen"].Kind != configmeta.SourceFile {
		t.Fatalf("empty metrics listen = %+v explicit=%v source=%+v", result.Config.Metrics, result.MetricsListenExplicit, result.Sources["metrics_listen"])
	}
	if !reflect.DeepEqual(result.Config.ProviderConfigs, []string{"providers/secret.json"}) {
		t.Fatalf("provider paths unexpectedly rebased: %v", result.Config.ProviderConfigs)
	}
	if got := result.Config.APIKeysFile; got != filepath.Join(dir, "keys", "accepted.json") {
		t.Fatalf("config-relative API key path = %q", got)
	}

	if _, err := Load(LoadOptions{Path: path, PathExplicit: true, Flags: parseFlags(t, "-log-level=")}); err == nil {
		t.Fatal("invalid winning file log level was accepted")
	}
	result = load(t, LoadOptions{Path: path, PathExplicit: true, Flags: parseFlags(t, "-log-level", "error"), DeriveInstanceID: fixedInstance("unused")})
	if result.Config.LogLevel != "error" {
		t.Fatalf("valid winning log flag = %q", result.Config.LogLevel)
	}
}

func TestDurationJSONUnionZeroAndValidation(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, dir, `{"models_dev_cache_ttl":0,"drain_delay":7,"shutdown_timeout":"0"}`)
	result := load(t, LoadOptions{Path: path, PathExplicit: true, DeriveInstanceID: fixedInstance("instance")})
	if result.Config.ModelsDevCacheTTL.Duration != 0 || result.Config.DrainDelay.Duration != 7*time.Second || result.Config.ShutdownTimeout.Duration != 0 {
		t.Fatalf("duration union = %+v", result.Config)
	}
	for _, tc := range []struct {
		name  string
		flags []string
		env   map[string]string
	}{
		{name: "explicit empty", flags: []string{"-drain-delay="}},
		{name: "negative flag", flags: []string{"-shutdown-timeout=-1s"}},
		{name: "negative environment", env: map[string]string{drainDelayEnvironment: "-1s"}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := Load(LoadOptions{Flags: parseFlags(t, tc.flags...), Getenv: getenv(tc.env), DeriveInstanceID: fixedInstance("instance")})
			if err == nil {
				t.Fatal("invalid duration was accepted")
			}
		})
	}
	result = load(t, LoadOptions{Path: path, PathExplicit: true, Getenv: getenv(map[string]string{drainDelayEnvironment: "  "}), DeriveInstanceID: fixedInstance("instance")})
	if result.Config.DrainDelay.Duration != 7*time.Second || result.Sources["drain_delay"].Kind != configmeta.SourceFile {
		t.Fatalf("blank environment did not preserve file = %v source=%+v", result.Config.DrainDelay.Duration, result.Sources["drain_delay"])
	}

	overflowPath := writeConfig(t, dir, `{"shutdown_timeout":9223372037}`)
	if _, err := Load(LoadOptions{Path: overflowPath, PathExplicit: true, DeriveInstanceID: fixedInstance("instance")}); err == nil || !strings.Contains(err.Error(), "overflows") {
		t.Fatalf("overflowed integer duration error = %v", err)
	}
}

func TestInstanceExplicitEmptyDerivesAndBlankEnvironmentIsAbsent(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, dir, `{"instance_id":"file-id"}`)
	result := load(t, LoadOptions{
		Path: path, PathExplicit: true,
		Flags:            parseFlags(t, "-instance-id="),
		Getenv:           getenv(map[string]string{instanceIDEnvironment: "env-id"}),
		DeriveInstanceID: fixedInstance("generated-id"),
	})
	if result.Config.InstanceID != "generated-id" || !result.InstanceIDExplicit || result.Sources["instance_id"].Kind != configmeta.SourceFlag {
		t.Fatalf("explicit-empty instance = %q explicit=%v source=%+v", result.Config.InstanceID, result.InstanceIDExplicit, result.Sources["instance_id"])
	}
	result = load(t, LoadOptions{Path: path, PathExplicit: true, Getenv: getenv(map[string]string{instanceIDEnvironment: " \t"}), DeriveInstanceID: fixedInstance("unused")})
	if result.Config.InstanceID != "file-id" || result.Sources["instance_id"].Kind != configmeta.SourceFile {
		t.Fatalf("blank environment instance = %q source=%+v", result.Config.InstanceID, result.Sources["instance_id"])
	}
}

func TestPathSelectionDiscoveryAndBases(t *testing.T) {
	home := t.TempDir()
	configDir := filepath.Join(home, ".config", "harness-model-proxy")
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		t.Fatal(err)
	}
	path := writeConfig(t, configDir, `{"api_keys_file":"relative/keys.json"}`)
	result := load(t, LoadOptions{Getenv: getenv(map[string]string{"HOME": home}), DeriveInstanceID: fixedInstance("instance")})
	if result.Path != path || result.PathExplicit || result.Config.APIKeysFile != filepath.Join(configDir, "relative", "keys.json") {
		t.Fatalf("discovery result = path %q explicit=%v keys=%q", result.Path, result.PathExplicit, result.Config.APIKeysFile)
	}

	result = load(t, LoadOptions{Path: "", PathExplicit: true, Getenv: getenv(map[string]string{"HOME": home}), DeriveInstanceID: fixedInstance("instance")})
	if result.Path != "" || !result.PathExplicit {
		t.Fatalf("explicit empty path discovered config: path=%q explicit=%v", result.Path, result.PathExplicit)
	}

	result = load(t, LoadOptions{Path: path, PathExplicit: true, Flags: parseFlags(t, "-api-keys-file", "cwd-relative.json"), DeriveInstanceID: fixedInstance("instance")})
	if result.Config.APIKeysFile != "cwd-relative.json" || !result.APIKeysFileExplicit || result.Sources["api_keys_file"].Kind != configmeta.SourceFlag {
		t.Fatalf("flag-relative key path = %q explicit=%v source=%+v", result.Config.APIKeysFile, result.APIKeysFileExplicit, result.Sources["api_keys_file"])
	}

	tmp := t.TempDir()
	fallbackDir := filepath.Join(tmp, "harness-model-proxy-config")
	if err := os.MkdirAll(fallbackDir, 0o755); err != nil {
		t.Fatal(err)
	}
	fallbackPath := writeConfig(t, fallbackDir, `{}`)
	result = load(t, LoadOptions{Getenv: getenv(map[string]string{"HOME": "", "TMPDIR": tmp}), DeriveInstanceID: fixedInstance("instance")})
	if result.Path != fallbackPath {
		t.Fatalf("TMPDIR discovery path = %q, want %q", result.Path, fallbackPath)
	}
}

func TestDefaultContextFallbackMetricsAndRetiredKeys(t *testing.T) {
	dir := t.TempDir()
	for _, value := range []string{"0", "-1"} {
		path := writeConfig(t, dir, `{"default_context_window":`+value+`,"metrics":{"listen":""}}`)
		result := load(t, LoadOptions{Path: path, PathExplicit: true, Flags: parseFlags(t, "-metrics-listen="), DeriveInstanceID: fixedInstance("instance")})
		if result.Config.DefaultContextWindow != llm.DefaultContextWindow || result.Sources["default_context_window"].Kind != configmeta.SourceDefault {
			t.Fatalf("context fallback for %s = %d source=%+v", value, result.Config.DefaultContextWindow, result.Sources["default_context_window"])
		}
		if result.Config.Metrics.Listen != defaultMetricsListen || !result.MetricsListenExplicit || result.Sources["metrics_listen"].Kind != configmeta.SourceDefault {
			t.Fatalf("explicit empty metrics = %+v explicit=%v source=%+v", result.Config.Metrics, result.MetricsListenExplicit, result.Sources["metrics_listen"])
		}
	}
	for _, retired := range []string{"api_keys", "cost_budget"} {
		path := writeConfig(t, dir, `{"`+retired+`":{}}`)
		if _, err := Load(LoadOptions{Path: path, PathExplicit: true}); err == nil || !strings.Contains(err.Error(), retired+" is no longer supported") {
			t.Fatalf("retired %s error = %v", retired, err)
		}
	}
}

func TestSnapshotExposesPathsButNeverReferencedSecrets(t *testing.T) {
	dir := t.TempDir()
	providerPath := filepath.Join(dir, "provider.json")
	keyPath := filepath.Join(dir, "keys.json")
	if err := os.WriteFile(providerPath, []byte(`{"api_key":"sk-super-secret","auth":{"client_secret":"oauth-secret"}}`), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(keyPath, []byte(`{"api_keys":[{"key":"hmp_plain_secret"}]}`), 0o600); err != nil {
		t.Fatal(err)
	}
	path := writeConfig(t, dir, `{"provider_configs":["provider.json"],"api_keys_file":"keys.json"}`)
	result := load(t, LoadOptions{Path: path, PathExplicit: true, DeriveInstanceID: fixedInstance("instance")})
	snapshot := Snapshot(result)
	projection := configmeta.Project(Catalog(), snapshot, true)
	encoded, err := json.Marshal(projection)
	if err != nil {
		t.Fatal(err)
	}
	text := string(encoded)
	for _, secret := range []string{"sk-super-secret", "oauth-secret", "hmp_plain_secret", "api_key\""} {
		if strings.Contains(text, secret) {
			t.Fatalf("snapshot leaked %q: %s", secret, text)
		}
	}
	if !strings.Contains(text, "provider.json") || !strings.Contains(text, "keys.json") {
		t.Fatalf("snapshot omitted safe path references: %s", text)
	}
	snapshot.Values["provider_configs"].([]string)[0] = "mutated"
	if result.Config.ProviderConfigs[0] != "provider.json" {
		t.Fatal("Snapshot aliased provider path list")
	}
}

func parseFlags(t *testing.T, args ...string) cli.Values {
	t.Helper()
	catalog := cli.MustCatalog(cli.Command{ID: "test", Name: "test", Runnable: true, Flags: CLIFlags()})
	invocation, err := catalog.Parse(args)
	if err != nil {
		t.Fatalf("parse flags %v: %v", args, err)
	}
	return invocation.Flags
}

func load(t *testing.T, options LoadOptions) Result {
	t.Helper()
	if options.DeriveInstanceID == nil {
		options.DeriveInstanceID = fixedInstance("test-instance")
	}
	result, err := Load(options)
	if err != nil {
		t.Fatal(err)
	}
	return result
}

func writeConfig(t *testing.T, dir, contents string) string {
	t.Helper()
	path := filepath.Join(dir, "config.json")
	if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

func getenv(values map[string]string) func(string) string {
	return func(name string) string { return values[name] }
}

func fixedInstance(value string) func() (string, error) {
	return func() (string, error) { return value, nil }
}
